DROP TABLE IF EXISTS boards;
DROP TABLE IF EXISTS attachments;
DROP TABLE IF EXISTS formulas;
DROP TABLE IF EXISTS constants;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS project_members;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS users;

DROP EXTENSION IF EXISTS "uuid-ossp";
